# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# Run Sketchybar together with AeroSpace
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart

# NOTE: for sketchybar to work: enable `desktop & dock -> displays have separate spaces` in system settings

# after-startup-command = ['exec-and-forget sketchybar'] # sketchybar disabled currently because of bad performance

# Notify Sketchybar about workspace change
# exec-on-workspace-change = ['/bin/bash', '-c',
#     'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
# ]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
# on-focus-changed = "move-mouse window-lazy-center"

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
# [gaps]
# inner.horizontal = 0
# inner.vertical =   0
# outer.left =       0
# outer.bottom =     0
# outer.top =        0
# outer.right =      0

# for builting the gap is 0 because of the notch (disabled because of sketchybar not active)
# gaps.outer.top = [
#     { monitor."built-in" = 0 },
#     37,
# ]

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, ctrl, alt, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# ctrl-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'
ctrl-enter = 'exec-and-forget open -n /Applications/iTerm.app'
ctrl-shift-enter = 'exec-and-forget open -na "/Applications/Brave Browser.app"'


# See: https://nikitabobko.github.io/AeroSpace/commands#layout
ctrl-slash = 'layout tiles horizontal vertical' # use to toggle horizontal and vertical split
# ctrl-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-h = 'focus left'
ctrl-j = 'focus down'
ctrl-k = 'focus up'
ctrl-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
ctrl-shift-h = 'move left'
ctrl-shift-j = 'move down'
ctrl-shift-k = 'move up'
ctrl-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
ctrl-shift-minus = 'resize smart -50'
ctrl-shift-equal = 'resize smart +50'

# fullscreen window
ctrl-f = 'fullscreen'

# quit window
ctrl-shift-q = 'close'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'
ctrl-0 = 'workspace 10'
ctrl-cmd-1 = 'workspace 11'
ctrl-cmd-2 = 'workspace 12'
ctrl-cmd-3 = 'workspace 13'
ctrl-cmd-4 = 'workspace 14'
ctrl-cmd-5 = 'workspace 15'
ctrl-cmd-6 = 'workspace 16'
ctrl-cmd-7 = 'workspace 17'
ctrl-cmd-8 = 'workspace 18'
ctrl-cmd-9 = 'workspace 19'
ctrl-cmd-0 = 'workspace 20'
# ctrl-b = 'workspace B' # for Browser
# ctrl-e = 'workspace E' # for File Explorer (Finder)
# ctrl-m = 'workspace M' # for Music
# ctrl-n = 'workspace N' # for Notes
# ctrl-p = 'workspace P' # for Photo Editing
# ctrl-t = 'workspace T' # for Terminal
# ctrl-v = 'workspace V' # for Video Editing

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'
ctrl-shift-6 = 'move-node-to-workspace 6'
ctrl-shift-7 = 'move-node-to-workspace 7'
ctrl-shift-8 = 'move-node-to-workspace 8'
ctrl-shift-9 = 'move-node-to-workspace 9'
ctrl-shift-0 = 'move-node-to-workspace 10'
ctrl-cmd-shift-1 = 'move-node-to-workspace 11'
ctrl-cmd-shift-2 = 'move-node-to-workspace 12'
ctrl-cmd-shift-3 = 'move-node-to-workspace 13'
ctrl-cmd-shift-4 = 'move-node-to-workspace 14'
ctrl-cmd-shift-5 = 'move-node-to-workspace 15'
ctrl-cmd-shift-6 = 'move-node-to-workspace 16'
ctrl-cmd-shift-7 = 'move-node-to-workspace 17'
ctrl-cmd-shift-8 = 'move-node-to-workspace 18'
ctrl-cmd-shift-9 = 'move-node-to-workspace 19'
ctrl-cmd-shift-0 = 'move-node-to-workspace 20'
# cmd-alt-ctrl-shift-b = 'move-node-to-workspace B' # for Browser
# cmd-alt-ctrl-shift-e = 'move-node-to-workspace E' # for File Explorer (Finder)
# cmd-alt-ctrl-shift-m = 'move-node-to-workspace M' # for Music
# cmd-alt-ctrl-shift-n = 'move-node-to-workspace N' # for Notes
# cmd-alt-ctrl-shift-p = 'move-node-to-workspace P' # for Photo Editing
# cmd-alt-ctrl-shift-t = 'move-node-to-workspace T' # for Terminal
# cmd-alt-ctrl-shift-v = 'move-node-to-workspace V' # for Video Editing

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
#ctrl-tab = 'workspace-back-and-forth' (disabled because of ctrl-tab in browser)
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
ctrl-shift-m = 'move-workspace-to-monitor --wrap-around left'

ctrl-shift-f = 'layout floating tiling'
ctrl-shift-a = 'layout tiling accordion'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
ctrl-shift-semicolon = 'mode service'
ctrl-r = 'mode resize'

# screenshot
cmd-ctrl-shift-alt-w = 'exec-and-forget screencapture -i -c'

# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

ctrl-shift-h = ['join-with left', 'mode main']
ctrl-shift-j = ['join-with down', 'mode main']
ctrl-shift-k = ['join-with up', 'mode main']
ctrl-shift-l = ['join-with right', 'mode main']


[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
