-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- #######################################################################################

-- HYPRLAND CONFIG

-- #######################################################################################

--###############

--## MONITORS ###

--###############

-- See https://wiki.hypr.land/Configuring/Monitors/

-- source = ~/.config/hypr/monitors.conf -> requires manual conversion
-- local monitors = require("monitors")

require("monitors")
-- source = ~/.config/hypr/workspaces.conf -> requires manual conversion
-- local workspaces = require("workspaces")
require("workspaces")

--##################

--## MY PROGRAMS ###

--##################

local terminal = "ghostty"

local fileManager = "dolphin"

--################

--## AUTOSTART ###

--################








-- exec = pkill hypridle; hypridle

-- use device specific config and fall back to defaults if it does not exist

-- exec = bash -c 'pkill hypridle; [ ! -f ~/.config/hypr/machine-spec.conf ] && echo -e "\$lock_timeout = 150\n\$screen_off_timeout = 300\n\$suspend_timeout = 600" > ~/.config/hypr/machine-spec.conf; hypridle'

--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

-- fixes for example the arduino ide scaling/blur issue

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

--####################

--## LOOK AND FEEL ###

--####################

-- disable scaling for XWayland apps (otherwise they could be blured) -> prefer inapp scaling

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 2,
        border_size = 1,
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = "rgba(27a762ff)",
            inactive_border = "rgba(303030ff)",
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 2,
        rounding_power = 2,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = false,
        --        NAME,           X0,   Y0,   X1,   Y1
        --           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    },
})
hl.curve("easeOutQuint", {
    type = "bezier",
    points = { { 0.23, 1 }, { 0.32, 1 } },
})
hl.curve("easeInOutCubic", {
    type = "bezier",
    points = { { 0.65, 0.05 }, { 0.36, 1 } },
})
hl.curve("linear", {
    type = "bezier",
    points = { { 0, 0 }, { 1, 1 } },
})
hl.curve("almostLinear", {
    type = "bezier",
    points = { { 0.5, 0.5 }, { 0.75, 1 } },
})
hl.curve("quick", {
    type = "bezier",
    points = { { 0.15, 0 }, { 0.1, 1 } },
})
hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
    misc = {
        -- disable_hyprland_logo = true
        -- disable_splash_rendering = true
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        kb_options = "compose:ralt",
        -- replaces sway's xkb_options compose:ralt
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false,
        },
    },
})

-- See https://wiki.hypr.land/Configuring/Gestures

hl.gesture({
    ["fingers"] = 3,
    ["direction"] = "horizontal",
    ["action"] = "workspace",
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

local mainMod = "SUPER"

-- ─── Discord (Shortcuts are passed to discord and need to be set there seperately) ───

hl.bind("F8", hl.dsp.pass({ window = "class:^discord$" }))

-- ─── Applications ────────────────────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("ghostty"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Return", hl.dsp.exec_cmd("brave"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exec_cmd("hyprctl dispatch exit"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Space", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("rofi -show drun -terminal ghostty"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("hyprctl reload"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.exec_cmd("rofi-rbw"))

-- ─── Focus (hjkl + arrows) ───────────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- ─── Move windows (hjkl + arrows) ────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.window.move({ direction = "left" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "J", hl.dsp.window.move({ direction = "down" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.window.move({ direction = "up" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.window.move({ direction = "right" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.move({ direction = "left" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.move({ direction = "right" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.move({ direction = "up" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.move({ direction = "down" }))

-- ─── Layout ──────────────────────────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.window.pin())

-- sticky window (≈ sway sticky toggle)

-- ─── Monitor focus and move ──────────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "M", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "O", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.workspace.move({ monitor = "l" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "O", hl.dsp.workspace.move({ monitor = "r" }))

-- ─── Workspaces 1–10 ─────────────────────────────────────────────────────────

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- ─── Workspaces 11–20 ────────────────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 1, hl.dsp.focus({ workspace = 11 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 2, hl.dsp.focus({ workspace = 12 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 3, hl.dsp.focus({ workspace = 13 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 4, hl.dsp.focus({ workspace = 14 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 5, hl.dsp.focus({ workspace = 15 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 6, hl.dsp.focus({ workspace = 16 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 7, hl.dsp.focus({ workspace = 17 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 8, hl.dsp.focus({ workspace = 18 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 9, hl.dsp.focus({ workspace = 19 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 0, hl.dsp.focus({ workspace = 20 }))

-- ─── Move to workspace 1–10 ──────────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- ─── Move to workspace 11–20 ─────────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "CONTROL + SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 11 }))

hl.bind(mainMod .. " + " .. "CONTROL + SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 12 }))

hl.bind(mainMod .. " + " .. "CONTROL + SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 13 }))

hl.bind(mainMod .. " + " .. "CONTROL + SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 14 }))

hl.bind(mainMod .. " + " .. "CONTROL + SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 15 }))

hl.bind(mainMod .. " + " .. "CONTROL + SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 16 }))

hl.bind(mainMod .. " + " .. "CONTROL + SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 17 }))

hl.bind(mainMod .. " + " .. "CONTROL + SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 18 }))

hl.bind(mainMod .. " + " .. "CONTROL + SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 19 }))

hl.bind(mainMod .. " + " .. "CONTROL + SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 20 }))

-- ─── Scratchpad ──────────────────────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- ─── Mouse workspace scroll ──────────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- ─── System ──────────────────────────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "period", hl.dsp.exec_cmd("systemctl suspend"))

-- ─── Notifications (swaync) ──────────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "N", hl.dsp.exec_cmd("swaync-client -t -sw"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "X", hl.dsp.exec_cmd("swaync-client --close-latest"))

-- ─── Screenshot: region → satty ──────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "SHIFT + CTRL + ALT" .. " + " .. "W", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | satty --filename - --early-exit"))

-- ─── Color picker ────────────────────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "SHIFT + CTRL + ALT" .. " + " .. "S", hl.dsp.exec_cmd("hyprpicker -a"))

-- ─── Clipboard history ───────────────────────────────────────────────────────

hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu -p \"Clipboard\" -display-columns 2 | cliphist decode | wl-copy"))

-- ─── Media / hardware keys ───────────────────────────────────────────────────

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- ─── Resize submap (≈ sway resize mode) ──────────────────────────────────────

hl.bind(mainMod .. " + " .. "R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
    hl.bind("left", hl.dsp.window.resize({ x = -20, y = 0, relative = true }))
    hl.bind("right", hl.dsp.window.resize({ x = 20, y = 0, relative = true }))
    hl.bind("up", hl.dsp.window.resize({ x = 0, y = -20, relative = true }))
    hl.bind("down", hl.dsp.window.resize({ x = 0, y = 20, relative = true }))
    hl.bind("Return", hl.dsp.submap("reset"))
    hl.bind("Escape", hl.dsp.submap("reset"))
    hl.bind(mainMod .. " + " .. "R", hl.dsp.submap("reset"))
end)


--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/

-- fix golden cheetah distance not updating in background (when window visible)

hl.window_rule({
    name  = "goldencheetah-keepawake",
    match = {
        class = "^(GoldenCheetah)$",
    },
    render_unfocused = true,
})

hl.window_rule({
    name  = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

hl.window_rule({
    name  = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = { 20, "monitor_h-120" },
    float = true,
})

-- ─── Floating windows ────────────────────────────────────────────────────────

hl.window_rule({
    name  = "float-calculator",
    match = {
        title = "Calculator",
    },
    float = true,
})

hl.window_rule({
    name  = "float-timer",
    match = {
        title = "Timer",
    },
    float = true,
})

hl.window_rule({
    name  = "float-mpv",
    match = {
        class = "mpv",
    },
    float = true,
})

hl.window_rule({
    name  = "float-imv",
    match = {
        class = "imv",
    },
    float = true,
})

hl.window_rule({
    name  = "float-zenity",
    match = {
        class = "zenity",
    },
    float = true,
})

hl.window_rule({
    name  = "float-cachyos-welcome",
    match = {
        class = "cachyos-welcome",
    },
    float = true,
})

-- ─── File picker popups ───────────────────────────────────────────────────────

hl.window_rule({
    name  = "float-brave-picker",
    match = {
        class = "brave-browser",
        title = "wants to open",
    },
    float = true,
    size = { 1000, 600 },
    center = true,
})

hl.window_rule({
    name  = "float-discord-picker",
    match = {
        class = "discord",
        title = "(?i)open",
    },
    float = true,
    size = { 1000, 600 },
    center = true,
})

-- ─── Screenshot annotation tool ──────────────────────────────────────────────

hl.window_rule({
    name  = "float-satty",
    match = {
        class = "com.gabm.satty",
    },
    float = true,
})

-- Autostart
hl.on("hyprland.start", function()
    -- Machine spec generator & hypridle launcher
    hl.exec_cmd([[bash -c 'pkill hypridle; [ ! -f ~/.config/hypr/machine-spec.conf ] && echo -e "$lock_timeout = 150\nscreen_off_timeout = 300\nsuspend_timeout = 600" > ~/.config/hypr/machine-spec.conf; hypridle']])

    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("swaync")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user restart xdg-desktop-portal-hyprland")
    hl.exec_cmd("systemctl --user restart xdg-desktop-portal")
end)

-- Exec (run every reload)
hl.on("config.reloaded", function()
    hl.exec_cmd("pkill waybar; waybar")
    hl.exec_cmd("pkill hyprpaper; hyprpaper")
    hl.exec_cmd("pkill hyprsunset; hyprsunset")
end)
