# Source the machine-specific variables
source = ~/.config/hypr/machine-spec.conf

general {
    lock_cmd         = hyprlock
    before_sleep_cmd = hyprlock
    after_sleep_cmd  = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout    = $lock_timeout
    on-timeout = hyprlock --grace 10
}

listener {
    timeout    = $suspend_timeout
    on-timeout = systemctl suspend
}


# TODO: implement light suspend
# listener {
#     timeout    = 165
#     # Turn off screens and mute audio instead of suspending
#     on-timeout = hyprctl dispatch dpms off && wpctl set-mute @DEFAULT_AUDIO@ 1
#     # Turn screens back on and unmute when you move the mouse
#     on-resume  = hyprctl dispatch dpms on && wpctl set-mute @DEFAULT_AUDIO@ 0
# }
