
general {
    lock_cmd         = hyprlock
    before_sleep_cmd = hyprlock
    after_sleep_cmd  = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

### Dim and Lock automatically after some time
listener {
    timeout    = 270
    on-timeout = ~/.config/hypr/scripts/dim.sh 0.1
    on-resume  = ~/.config/hypr/scripts/dim.sh 1.0
}
listener {
    timeout    = 300
    on-timeout = hyprlock
}
