general {
    grace = 10                       # 10 seconds where moving the mouse unlocks without a password
}

background {
    monitor =
    path = screenshot                # Takes a slice of your current screen
    color = rgba(25, 20, 20, 0.8)    # Adds a 50% dark tint
    blur_passes = 3                  # Blurs it slightly so you know it's "locked"
}

input-field {
    monitor  =
    size     = 300 50

    outline_thickness = 2
    outer_color       = rgb(9ab4c4)   # $text from sway theme
    inner_color       = rgb(222222)   # $pill_bg from sway theme
    font_color        = rgb(9ab4c4)

    placeholder_text  = <i>Password...</i>
    fail_text         = <b>$FAIL ($ATTEMPTS)</b>

    position = 0, -100
    halign   = center
    valign   = center
}
