-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Generated by nwg-displays on 2026-04-13 at 19:15:25. Do not edit manually.

hl.monitor({
    output   = "desc:Hewlett Packard HP E232 3CQ7330LGG",
    mode     = "1920x1080@60.0",
    position = "6400x636",
    scale    = 1.0,
})

hl.monitor({
    output   = "desc:BNQ BenQ LCD AAE04512SL0",
    disabled = true,
})

hl.monitor({
    output   = "desc:Acer Technologies XV272 P 0x03716008",
    mode     = "1920x1080@120.0",
    position = "1920x636",
    scale    = 1.0,
})

hl.monitor({
    output   = "desc:Acer Technologies XV272U V R3351587D4204",
    mode     = "2560x1440@143.91",
    position = "3840x471",
    scale    = 1.0,
})
