-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Generated by nwg-displays on 2026-05-07 at 14:22:50. Do not edit manually.

hl.workspace_rule({
    workspace = 1,
    monitor = "desc:Acer Technologies XV272U V R3351587D4204",
    default = true,
})
