-- vim.keymap.set('n', '<leader>mt', require('treesj').toggle)
--
-- -- vim.keymap.set('n', '<leader>ms', require('treesj').split)
-- vim.keymap.set('n', '<leader>mj', require('treesj').join)
--
-- -- For extending default preset with `recursive = true`
-- vim.keymap.set('n', '<leader>Mt', function()
--     require('treesj').toggle({ split = { recursive = true } })
-- end)
--
-- vim.keymap.set('n', '<leader>Ms', function()
--     require('treesj').split({ split = { recursive = true } })
-- end)
-- vim.keymap.set('n', '<leader>Mj', function()
--     require('treesj').join({ split = { recursive = true } })
-- end)
